name: face-recog
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.0
  - freetype=2.14.1
  - graphite2=1.3.14
  - harfbuzz=11.4.5
  - icu=75.1
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.1
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - mkl=2024.2.2
  - munkres=1.1.4
  - numpy=1.26.4
  - openjpeg=2.5.4
  - openssl=3.5.3
  - pandas=2.2.3
  - pcre2=10.45
  - pillow=10.4.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyparsing=3.2.5
  - pyside6=6.8.3
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.8.3
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - blinker==1.9.0
      - cachetools==5.5.2
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colorama==0.4.6
      - cython==3.1.4
      - deprecation==2.1.0
      - dlib==20.0.0
      - easydict==1.13
      - exceptiongroup==1.3.0
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - fastapi==0.103.0
      - filelock==3.19.1
      - fire==0.7.1
      - flask==2.2.5
      - flask-cors==4.0.2
      - flatbuffers==25.9.23
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - gotrue==2.9.1
      - grpcio==1.75.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h2==4.3.0
      - h5py==3.14.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.25.2
      - hyperframe==6.1.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==6.11.0
      - insightface==0.7.3
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.11.3
      - lazy-loader==0.4
      - libclang==18.1.1
      - lz4==4.4.4
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mediapipe==0.10.9
      - ml-dtypes==0.5.3
      - mtcnn==1.0.0
      - namex==0.1.0
      - narwhals==2.5.0
      - networkx==3.4.2
      - onnx==1.19.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==23.2
      - postgrest==0.16.11
      - prettytable==3.16.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - pysocks==1.7.1
      - python-dotenv==1.0.0
      - pyyaml==6.0.2
      - realtime==1.0.6
      - referencing==0.36.2
      - requests==2.32.5
      - retina-face==0.0.17
      - rich==13.9.4
      - rpds-py==0.27.1
      - scikit-image==0.25.2
      - simsimd==6.5.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soupsieve==2.8
      - starlette==0.27.0
      - storage3==0.7.7
      - streamlit==1.28.0
      - strenum==0.4.15
      - stringzilla==4.0.14
      - supabase==2.3.8
      - supafunc==0.3.3
      - tenacity==8.5.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-cpu==2.16.1
      - tensorflow-intel==2.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tf-keras==2.20.1
      - tifffile==2025.5.10
      - toml==0.10.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzlocal==5.3.1
      - urllib3==2.5.0
      - uvicorn==0.23.2
      - validators==0.35.0
      - watchdog==4.0.2
      - watchfiles==1.1.0
      - wcwidth==0.2.14
      - websockets==12.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - zipp==3.23.0

