name: face-recog
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - sqlalchemy
  - opencv
  - dlib
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - streamlit
      - fastapi
      - uvicorn
      - deepface
      - face-recognition
